[package]
name = "petstoreserver"
version = "0.1.0"
edition = "2021"

[dependencies]
petstoreapi = { path="../petstore-api"}
async-trait = "0.1.83"
http = "1.1.0"
axum = "0.7.7"
axum-extra = "0.9.4"
bytes = "1.7.2"
tracing-subscriber = "0.3.18"
tokio = "1.40.0"
